baseurl = ""
languageCode = "en-us"
title = "Ruff'n'Ready"
theme = "hugo-creative-theme"
googleAnalytics = "UA-120221892-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.


	name = "Ruff'n'Ready"
	description = "Raw Food Nutrition"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Ruff'n'Ready"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Products"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "The best raw food for your pet"
		subtitle   = "Ruff'n'Ready takes the guesswork out of raw food."
		buttonText = "Find out more"
		logo = "/img/ruffandready.png"

		# Meet The Team section
		[params.bio]
			# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
			name     = "Meet The Team"
			subtitle = ""



	# About section
	[params.about]
		headline    = "We go the extra mile to make your pet smile!"
		description = "We are constantly searching out the finest ingredients for 100% Protein meals <br>Your furry friend deserves the best!"
		buttonText  = "Meet the Team!"
		content =  "\"Ruff'n'Ready is Calgary's premiere raw food provider. We offer complete meal packages that keep things healthy and exciting for your pet\""
		logo = "/img/ruffandready_notext.png"

	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-cutlery"
            title = "Quality Food"
            description = "We use diverse and top quality ingredients. All our food is also 100% protein"

        [[params.services.list]]
					icon = "fa-list"
					title = "Meal Planning"
					description = "Keep meals exciting and healthy with diverse mixed packs"

				[[params.services.list]]
					icon = "fa-certificate"
					title = "Certified Facilities"
					description = "Our facilities are fully certified"

        [[params.services.list]]
          icon = "fa-heart"
          title = "Made with Love"
          description = "We love our pets and feed them the best proteins we can get!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

				# bios modals
			[params.bios.modal]
						title = "Title"
						role = "Role"
						biography = "Biography"
						buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Let us take some of the guesswork out of raw food with our high quality Canadian sourced meals"

		[params.aside.button]
			text = "Coming Soon - Sign up Today"
			## Change this back to - link = "http://ruffandready.bigcartel.com" once site live also change button to Order Now
			link = "https://mailchi.mp/bd7ddacd2cea/ruffnready-coming-soon"


	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your order but have a few questions? Let us know!"
		phone = "403-461-5998"
		email = "info@ruffnready.ca"

	# Google Maps section - removed for now
	 [params.location]
	 	latitude  = "50.986"
	 	longitude = "-113.974"
	 	maps_api_key = ""
