baseurl = ""
languageCode = "en-us"
title = "Ruff'n'Ready"
theme = "hugo-creative-theme"
googleAnalytics = "UA-120221892-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.

	name = "Ruff'n'Ready"
	description = "Raw Food Nutrition"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "Ruff'n'Ready"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Products"
			contact   = "Contact"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "We go the extra mile to make your pet smile"
		subtitle   = "Providing Alberta and BC's best raw food proteins for your pet. We aim for the highest quality at affordable prices"
		buttonText = "Find out more"
		logo = "/img/ruffandready.png"



#Highlights
[params.highlights]
title = "Highlights"
[[params.highlights.list]]
	icon = "fa-trophy"
	title = "Best Quality"
	headline = "We work exclusively with inspected facilities regulated to human standards in both Alberta and British Columbia"

[[params.highlights.list]]
	icon = "fa-money"
	title = "Value"
	headline = "Our raw food products are all 100% protein so your not paying for frozen fruits and veggies"

	[[params.highlights.list]]
		icon = "fa-map"
		title = "Local Ingredients"
		headline = "We source locally in Alberta and British Columbia and process only the best ingredients we can find"

		# Meet The Team section
		[params.bio]
			# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
			name     = "Meet The Team"
			subtitle = ""

			# Meet The Team section
			[params.info]
				# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
				name     = "Why we started Ruff'n'Ready"
				subtitle = ""

	# About section
	[params.about]
		headline    = "We go the extra mile to make your pet smile!"
		description = "We are constantly searching out the finest ingredients for 100% raw food protein meals<br>because your furry friend deserves the best!"
		buttonText  = "Meet the Team!"
		content =  "\"Ruff'n'Ready is Alberta's premiere raw food provider. We offer complete raw food meal packages that keep things healthy and exciting for your pet\""
		logo = "/img/ruffandready_notext.png"

	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-cutlery"
            title = "Quality Food"
            description = "We use diverse, top quality, and local ingredients. All our raw food is 100% protein"

        [[params.services.list]]
					icon = "fa-list"
					title = "Meal Planning"
					description = "Keep meals exciting and healthy with our diverse protein based raw food selections."

				[[params.services.list]]
					icon = "fa-certificate"
					title = "Certified Facilities"
					description = "Our facilities are all provincially or federally certified to human standards and in either British Columbia or Alberta"

        [[params.services.list]]
          icon = "fa-heart"
          title = "Made with Love"
          description = "We love our pets and feed them the best proteins we can source!"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

  	# bios modals
			[params.bios.modal]
						title = "Title"
						role = "Role"
						biography = "Biography"
						buttonText = "Close"

		# food-info modals
		[params.foodInfo.modal]
			name = "Name"
			description = "Description"
			benefits = "Benefits"
			nutrition = "Nutrition"
			buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Let us take some of the guesswork out of raw food with our high quality Canadian sourced meals"

		[params.aside.button]
			text = "Why Ruff'n'Ready"
			link = "/info"

			[[params.aside.list]]
					icon = "fa-leaf"
					title = "Fruits and Veggies"
					description = "Info on diversifying your pets diet"
					link = "/food-info"
			[[params.aside.list]]
					icon = "fa-shopping-basket"
					title = "Where to Buy"
					description = "Where to buy Ruff'n'Ready in store"
					link = "/where-to-buy"
			[[params.aside.list]]
					icon = "fa-balance-scale"
					title = "Food Calculator"
					description = "Calculate how much to feed your pet"
				  link = "/food-calc"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Are you Ruff'n'Ready but still have a few questions? Let us know!"
		phone = "403-461-5998 | 403-804-8188"
		email = "info@ruffnready.ca"
		address = "PO Box 87054 - Douglas Square Calgary, Alberta, Canada T2Z-3V7"
		endnote = "Ruff'n'Ready is a premium raw dog food provider sourcing and producing high quality raw foods in both Alberta and British Columbia"

	# Google Maps section - removed for now
	 [params.location]
	 	latitude  = "50.986"
	 	longitude = "-113.974"
	 	maps_api_key = ""
