baseurl = ""
languageCode = "en-us"
title = "Ruff'n'Ready"
theme = "hugo-creative-theme"
googleAnalytics = "UA-120221892-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.

	###Prior to going live - change 'projectss' to 'projects'

	name = "Ruff and Ready"
	description = "Raw Food Nutrition"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Ruff & Ready"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Products"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "The best home delivered raw food for your pet"
		subtitle   = "Why waste time going out when you can have complete raw meals delivered directly to your home"
		buttonText = "Find out more"
		logo = "/img/ruffandready.png"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "The finest ingredients - the best service. You and your furry friend deserve it!"
		buttonText  = "Check it out!"
		content =  "\"Ruff'n'Ready is Calgary's premiere raw food provider. We offer complete meal packages that keep things healthy and exciting for your pet\""
		logo = "/img/ruffandready_notext.png"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-cutlery"
            title = "Quality Food"
            description = "We use diverse and top quality ingredients"

        [[params.services.list]]
					icon = "fa-list"
					title = "Meal Planning"
					description = "Keep meals exciting and healthy with diverse mixed packs"

				[[params.services.list]]
					icon = "fa-truck"
					title = "Free Delivery"
					description = "You order, and we deliver! It's as simple as that"

        [[params.services.list]]
          icon = "fa-heart"
          title = "Made with Love"
          description = "We love our pets and feed them the best we can offer!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Let us take some of the guesswork out of raw food"

		[params.aside.button]
			text = "Coming Soon - Sign up Today"
			## Change this back to - link = "http://ruffandready.bigcartel.com" once site live also change button to Order Now
			link = "https://mailchi.mp/bd7ddacd2cea/ruffnready-coming-soon"


	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your order but have a few questions? Let us know!"
		phone = "587-433-1337"
		email = "info@ruffandready.ca"

	# Google Maps section - removed for now
	 [params.location]
	 	latitude  = "50.986"
	 	longitude = "-113.974"
	# 	maps_api_key = ""
